### ISSUE TITLE
Can't add someone who is already registered as a staff member

### ISSUE THREAD

**Issue by jfly** [cubing/ccm#274]
Fixing this should be as simple as looking up the existing registration, rather than creating a new one.

```javascript
I20151113-14:24:06.050(-8)? Exception while invoking method 'addStaffMembers' MongoError: insertDocument :: caused by :: 11000 E11000 duplicate key error index: meteor.registrations.$competitionId_1_uniqueName_1  dup key: { : "XPnofeSLPQCHQxTAe", : "Patricia Li" }
I20151113-14:24:06.050(-8)?     at Object.Future.wait (/home/jeremy/.meteor/packages/meteor-tool/.1.1.10.o1dqyn++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
I20151113-14:24:06.051(-8)?     at [object Object].<anonymous> (meteor://💻app/packages/meteor/helpers.js:119:1)
I20151113-14:24:06.051(-8)?     at [object Object].MongoConnection.(anonymous function) [as insert] (meteor://💻app/packages/mongo/mongo_driver.js:736:1)
I20151113-14:24:06.051(-8)?     at [object Object].Mongo.Collection.(anonymous function) (meteor://💻app/packages/mongo/collection.js:590:1)
I20151113-14:24:06.051(-8)?     at [object Object].Mongo.Collection.(anonymous function) [as insert] (meteor://💻app/packages/aldeed_collection2/packages/aldeed_collection2.js:195:1)
I20151113-14:24:06.051(-8)?     at meteor://💻app/server/methods.js:462:60
I20151113-14:24:06.051(-8)?     at Array.forEach (native)
I20151113-14:24:06.051(-8)?     at [object Object].Meteor.methods.addStaffMembers (meteor://💻app/server/methods.js:439:17)
I20151113-14:24:06.051(-8)?     at maybeAuditArgumentChecks (meteor://💻app/livedata_server.js:1698:12)
I20151113-14:24:06.051(-8)?     at meteor://💻app/livedata_server.js:708:19
I20151113-14:24:06.051(-8)?     - - - - -
I20151113-14:24:06.052(-8)?     at Object.toError (/home/jeremy/.meteor/packages/npm-mongo/.1.4.39_1.195xa1v++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/utils.js:114:11)
I20151113-14:24:06.052(-8)?     at /home/jeremy/.meteor/packages/npm-mongo/.1.4.39_1.195xa1v++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/collection/core.js:116:29
I20151113-14:24:06.052(-8)?     at /home/jeremy/.meteor/packages/npm-mongo/.1.4.39_1.195xa1v++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1197:7
I20151113-14:24:06.052(-8)?     at /home/jeremy/.meteor/packages/npm-mongo/.1.4.39_1.195xa1v++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1905:9
I20151113-14:24:06.052(-8)?     at Server.Base._callHandler (/home/jeremy/.meteor/packages/npm-mongo/.1.4.39_1.195xa1v++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
I20151113-14:24:06.052(-8)?     at /home/jeremy/.meteor/packages/npm-mongo/.1.4.39_1.195xa1v++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
I20151113-14:24:06.052(-8)?     at [object Object].MongoReply.parseBody (/home/jeremy/.meteor/packages/npm-mongo/.1.4.39_1.195xa1v++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
I20151113-14:24:06.052(-8)?     at [object Object].<anonymous> (/home/jeremy/.meteor/packages/npm-mongo/.1.4.39_1.195xa1v++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)
I20151113-14:24:06.052(-8)?     at [object Object].emit (events.js:95:17)
I20151113-14:24:06.052(-8)?     at [object Object].<anonymous> (/home/jeremy/.meteor/packages/npm-mongo/.1.4.39_1.195xa1v++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
```

**Comment by jfly** [comment]
Fix in https://github.com/cubing/ccm/commit/0b022a2879ab3bed52cf10b70fa4126ea5413db6!
