### ISSUE TITLE
Exception from sub competition id Error: Match error: Expected string, got null

### ISSUE THREAD

**Issue by jfly** [cubing/ccm#331]
```
I20160906-12:13:14.596(-7)? Exception from sub competition id 9D9mB3maLzH4TJ2wE Error: Match error: Expected string, got null
I20160906-12:13:14.597(-7)?     at exports.check (packages/check/match.js:34:1)
I20160906-12:13:14.599(-7)?     at Subscription._handler (imports/startup/server/publications.js:50:3)
I20160906-12:13:14.599(-7)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1704:12)
I20160906-12:13:14.599(-7)?     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1026:17)
I20160906-12:13:14.600(-7)?     at Session._startSubscription (packages/ddp-server/livedata_server.js:845:9)
I20160906-12:13:14.600(-7)?     at Session.sub (packages/ddp-server/livedata_server.js:617:12)
I20160906-12:13:14.601(-7)?     at packages/ddp-server/livedata_server.js:551:43
I20160906-12:13:14.601(-7)? Sanitized and reported to the client as: Match failed [400]
I20160906-12:13:14.602(-7)? 
```

**Comment by coder13** [comment]
https://github.com/cubing/ccm/blob/overhaul/imports/ui/pages/layout.jsx#L192

Is the cause.
When on the home page, props.competitionUrlId is obviously not defined.
